name: Cypress tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # baixa o código do repositório
      - uses: actions/checkout@v4

      # instala o Node
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # instala dependências do seu package.json
      - name: Install dependencies
        run: npm ci

      # executa o Cypress e grava no Dashboard
      - name: Run Cypress tests and record
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: npx cypress run --record